/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Purchases_Create_Update = require('./code/before-purchases-create-update');
const on_Redemptions_Redemption = require('./code/on-redemptions-redemption');

class myNamespaceSrv extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'Purchases', async (request) => {
            await before_Purchases_Create_Update(request);
        });

        this.on('redemption', 'Redemptions', async (request) => {
            return on_Redemptions_Redemption(request);
        });

        return super.init();
    }
}


module.exports = {
    myNamespaceSrv
};